name: 错误报告
description: 你认为某个功能出现了问题
title: "[错误]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        > 错误报告的标题应简短明了。
        > 使用相关关键词以提高可搜索性。
        > 不要留空，但也不要在标题中放入完整的错误日志。
  - type: checkboxes
    attributes:
      label: 检查清单
      description: |
        请执行基本的调试，查看是否是你的配置导致了问题。
        基本调试步骤：
        　1. 更新 - 有时问题只需更新即可解决
        　2. 备份并还原你的 .env 调整 - 检查问题是否由错误配置引起
        　3. 在不同目录尝试全新安装 - 查看干净安装是否能解决问题
        在提交错误报告之前，请检查该问题是否最近已被报告过。
      options:
        - label: 该问题在全新安装时存在
        - label: 该问题在当前版本中存在
        - label: 该问题之前未被报告过
        - label: 该问题之前已被报告但尚未修复
  - type: markdown
    attributes:
      value: |
        > 请尽可能详细地填写此表单。不要忘记添加"操作系统"信息，并在可能的情况下提供截图
  - type: textarea
    id: what-did
    attributes:
      label: 发生了什么？
      description: 请以清晰简洁的方式告诉我们发生了什么
      placeholder: |
        应用程序在启动时崩溃。
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 重现问题的步骤
      description: 请提供详细的逐步说明，说明如何重现该错误
      placeholder: |
        1. 前往 ...
        2. 按下 ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: what-should
    attributes:
      label: 应该发生什么？
      description: 告诉我们你认为正常行为应该是什么
      placeholder: |
        它应该 ...
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: 你使用什么浏览器访问仪表板？
      multiple: true
      options:
        - Mozilla Firefox
        - Google Chrome
        - Brave
        - Apple Safari
        - Microsoft Edge
        - Android
        - iOS
        - Other
  - type: dropdown
    id: hosting
    attributes:
      label: 你在哪里运行应用程序？
      multiple: false
      options:
        - 本地
        - 使用虚拟化在本地运行（例如 Docker）
        - 云服务（例如 AWS, GCP, Azure）
  - type: input
    id: operating-system
    attributes:
      label: 你使用什么操作系统？
      placeholder: |
        Windows 11 / MacOS 15.3.2
  - type: textarea
    id: logs
    attributes:
      label: 控制台日志
      description: 请提供从启动 UI 到错误发生后的完整命令行/终端日志。如果很长，请提供 pastebin 或类似服务的链接。
      render: Shell
    validations:
      required: true
  - type: textarea
    id: misc
    attributes:
      label: 附加信息
      description: | 
        请向我们提供任何相关的附加信息或上下文。
        示例：
        　我最近更新了软件包。