name: 功能请求
description: 为这个项目提出一个想法
title: "[功能请求]: "
labels: ["enhancement", "triage"]

body:
  - type: checkboxes
    attributes:
      label: 是否已有相关问题？
      description: 请搜索是否已经存在关于你想要的功能的问题，以及它是否在最近的构建/提交中未实现。
      options:
        - label: 我已经搜索了现有问题并检查了最近的构建/提交
          required: true
  - type: markdown
    attributes:
      value: |
        *请尽可能详细地填写此表单，如果可能，请提供功能的截图和/或插图*
  - type: textarea
    id: feature
    attributes:
      label: 你的功能会做什么？
      description: 请以清晰简洁的方式告诉我们你的功能，以及它将解决什么问题
    validations:
      required: true
  - type: textarea
    id: workflow
    attributes:
      label: 建议的工作流程
      description: 请提供关于你希望如何访问和使用该功能的逐步信息
      value: |
        1. 前往 .... 
        2. 按下 ....
        3. ...
    validations:
      required: true
  - type: textarea
    id: misc
    attributes:
      label: 附加信息
      description: 在此处添加关于功能请求的任何其他上下文或截图。